# Generated by Django 2.1.5 on 2020-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200812_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription',
            field=models.TextField(max_length=1000),
        ),
    ]
